#!/bin/csh
# This is the Unix/Linux shell script to start up NetCheck.
# To make this Linux/Unix script executable, use "chmod +x NetCheck".
# Modify NetCheck.xml to suit your needs before running this.
# Then run "./NetCheck" from a command prompt.
# Use "./NetCheck -testMode" to just send emails to the NetCheck administrator.

set commandLine=$0
set thisDir=`echo commandLine | dirname $0`
java -cp $thisDir/classes:$thisDir/lib/mail.jar:$thisDir/lib/netcdfAll-latest.jar:$thisDir/lib/slf4j-jdk14.jar:$thisDir/lib/activation.jar gov.noaa.pfel.coastwatch.netcheck.NetCheck NetCheck.xml $1 $2
