#!/bin/csh
#
# usage: ValidateDataSetProperties
#
# ValidateDataSetProperties makes sure that DataSet.properties has all of 
# the required information for each of the data sets listed in 
# DataSet.properties' validDataSets.
# Don't run this on the coastwatch computer.
#
# To make this Linux/Unix script executable, use "chmod +x ValidateDataSetProperties".
#
# 2006-10-09
# NOAA/Bob Simons  bob.simons@noaa.gov
#

set commandLine=$0
set tDir=`echo commandLine | dirname $0`
set cp1="$tDir/classes:$tDir/lib/netcdfAll-latest.jar:$tDir/lib/slf4j-jdk14.jar:"
set cp2="$tDir/lib/activation.jar:$tDir/lib/lucene-core.jar:$tDir/lib/mail.jar"
set cp0="$cp1$cp2"

java -cp $cp0 -Xms1000M -Xmx1000M gov.noaa.pfel.coastwatch.ValidateDataSetProperties

# finished 
