{
 "title": "Fleet Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "ERDDAP Versions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(version_full) (ERDDAP_build_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JDK Versions",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(version) (jvm_runtime_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Feature Flag Settings",
   "type": "gauge",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(feature_flags) (feature_flags)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}