
# NOTE: This docker-compose file has been deprecated.
# The monitoring services have been moved to the root docker-compose.yml file
# and can be enabled with the "monitoring" profile:
#
# docker-compose --profile monitoring up
#
# Please use the root configuration instead of this file.
