global:
  scrape_interval: 15s
  evaluation_interval: 15s

  alerting:
    alertmanagers:
      - static_configs:
          - targets:
            # - alertmanager:9093

  rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

  scrape_configs:
    - job_name: 'erddap'
      scrape_interval: 30s
      metrics_path: '/erddap/metrics'
    scheme: 'http'
    honor_labels: true
      static_configs:
      - targets: ['erddap-erddap-1:8080']
          labels:
            instance: 'erddap-primary'
            region: 'primary'

    # Example of monitoring multiple ERDDAP instances
    # - job_name: 'erddap-secondary'
    #   scrape_interval: 30s
    #   metrics_path: '/erddap/metrics'
    #   static_configs:
    #     - targets: ['erddap-secondary:8080']
    #       labels:
    #         instance: 'erddap-secondary'
    #         region: 'secondary'
