name: Pull Build and test ERDDAP

# no permissions by default
permissions: {}

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
      with:
        persist-credentials: false
    - name: Free Disk Space Before Build
      run: |
        echo "Disk space before cleanup:"
        df -h
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        sudo rm -rf /usr/local/.ghcup
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo rm -rf /usr/local/lib/android/sdk/ndk
        sudo apt-get clean
        echo "Disk space after cleanup:"
        df -h
    - name: Set up JDK 21
      uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00  # v4.7.1
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build and test with Maven
      run: >
        mvn --batch-mode
        -Dgcf.skipInstallHooks=true
        -Dmaven.test.redirectTestOutputToFile=true
        -Ddownload.unpack=true
        -Ddownload.unpackWhenChanged=false
        clean verify
